name: my_weather_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  get_it: ^8.0.3
  fpdart: ^1.1.1
  flutter_dotenv: ^5.2.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  cached_network_image: ^3.4.1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 500
    - family: FuturaCondensed
      fonts:
        - asset: assets/fonts/FuturaCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/FuturaCondensed-ExtraBold.ttf
          weight: 900
